# Generated by Django 5.1.1 on 2025-04-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_3d_url',
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(help_text='Upload a GLB/GLTF file for AR', null=True, upload_to='models_3d/'),
        ),
    ]
