# Generated by Django 5.1.1 on 2025-04-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_customuser_options_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
